Usuarios/config/routes.rb
Rails.application.routes.draw do
	resources :usuarios

end

Usuarios/app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

Usuarios/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Usuarios/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		#@usuario=Usuario.new
    @usuarios=Usuario.all
	end

	def new
		@usuario = Usuario.new
	end

	def create
		@usuario = Usuario.new(usuario_params)
		if @usuario.save
			redirect_to @usuario
		else
			render 'new'
		end
	end

	def edit
		@usuario=Usuario.find(params[:id])
    @usuario.save
	end

	def show
    @usuario = Usuario.find(params[:id])
	end

	def update

		if @usuario.update(usuario_params)
			redirect_to @usuario
		else
			render 'edit'
		end
	end

	def destroy
		@usuario=Usuario.find(params[:id])
  	@usuario.destroy
    redirect_to  usuarios_path
	end
	
  private

	def usuario_params
		params.require(:usuario).permit(:name, :apellidoP, :apellidoM, :edad, :email)
	end

	def set_user
		@usuario = Usuario.find(params[:id])
	end
end

Usuarios/app/helpers/application_helper.rb
module ApplicationHelper
end

Usuarios/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Usuarios/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usuarios</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Usuarios/app/views/usuarios/edit.html.erb
<div id=fondo>
<h1><u><i>Formulario</i></u></h1>

<%= form_for @usuario do |f| %>
<%= f.text_field :name, placeholder: 'Nombre', :required  => '' %>
		<%= f.text_field :apellidoP, placeholder: 'Apellido Paterno' %>
		<%= f.text_field :apellidoM, placeholder:'Apellido Materno' %>
		<%= f.number_field :edad, placeholder: 'Edad', :required=> '' %>
		<%= f.email_field :email, placeholder: 'E-mail', :required => '' %>
		<br>
    <center><%= f.submit%></center>
<% end %>
<center><%= link_to 'home', usuarios_path, class: "btn btn-info" %></center>
</div>

Usuarios/app/views/usuarios/index.html.erb
<div id=fondo>
<h1><u><i>REGISTROS</i></u></h1>

<center><%= link_to "new", new_usuario_path, class: "btn btn-info"%><center>
</div>
<table class="usuarios">
    <tbody>
    <tr>
        <th>Nombre</th>
        <th>Edad</th>
        <th>E-mail</th>
        <th>Editar</th>
        <th>Eliminar</th>
    </tr>
    <% @usuarios.each do |usuario|%>
    <tr>
        <td><%= "#{usuario.name} #{usuario.apellidoP} #{usuario.apellidoM}" %></td>
        <td><%= "#{usuario.edad} años" %></td>
        <td><%= usuario.email %></td>
        <td><%= link_to "Update", edit_usuario_path(usuario)%></td>
        <td><%= link_to "Destroy",  usuario_path(usuario), method: :delete, data: {confirm: 'Estas seguro?'} %></td>
    </tr>
    <%end%>
    </tbody>
</table>

Usuarios/app/views/usuarios/new.html.erb
<div id=fondo>
<h1><u><i>Formulario</i></u></h1>

<%= form_for @usuario do |f| %>
<%= f.text_field :name, placeholder: 'Nombre', :required  => '' %>
		<%= f.text_field :apellidoP, placeholder: 'Apellido Paterno' %>
		<%= f.text_field :apellidoM, placeholder:'Apellido Materno' %>
		<%= f.number_field :edad, placeholder: 'Edad', :required=> '' %>
		<%= f.email_field :email, placeholder: 'E-mail', :required => '' %>
		<br>
<center><%= f.submit%></center>
<% end %>
<center><%= link_to 'home', usuarios_path, class: "btn btn-info" %></center>
</div>

Usuarios/app/views/usuarios/show.html.erb
<table class="usuarios">
    <tbody>
    <tr>
        <th>Nombre</th>
        <th>Edad</th>
        <th>E-mail</th>
        <th>Editar</th>
        <th>Eliminar</th>
    </tr>
    
    <tr>
        <td><%= "#{@usuario.name} #{@usuario.apellidoP} #{@usuario.apellidoM}" %></td>
        <td><%= "#{@usuario.edad} años" %></td>
        <td><%= @usuario.email %></td>
        <td><%= link_to "Update", edit_usuario_path(@usuario)%></td>
        <td><%= link_to "Destroy",  usuario_path(@usuario), method: :delete, data: {confirm: 'Estas seguro?'} %></td>
    </tr>

    </tbody>
</table>
<div id="fondo">
<center><%= link_to 'home', usuarios_path, class: "btn btn-info" %></center>
</div>